name: sleap_m1

channels:
    - defaults
    - conda-forge
    - apple

dependencies:
    - python=3.8
    - shapely=1.7.1
    - h5py=3.1.0
    - scipy=1.7.3
    - tensorflow-deps=2.7.0
    - pip
    - pip:
        - "--editable=./"
        - "--requirement=./dev_requirements.txt"