name: sleap

channels:
- defaults
- apple
- conda-forge

dependencies:
- python=3.8
- shapely=1.7.1
- tensorflow-deps
- pandas
- scikit-image
- scikit-learn
- python-rapidjson
- psutil
- pip
- pip:
    - tensorflow-macos
    - tensorflow-metal
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"
